apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator
resources:
  # ensure you update the ref in this line to the latest version
  - https://github.com/adyanth/cloudflare-operator.git/config/default?ref=v0.13.1
  - cf-external-secret.yaml
