apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/aredan/talos-incus-agent/v6.22.1/deploy/daemonset.yaml
patches:
  - target:
      kind: Namespace
      name: incus-agent
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-1"
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: privileged
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit
        value: privileged
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: privileged
  - target:
      kind: DaemonSet
      name: incus-agent
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "1"
