---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bitwarden-access-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgAdxcVx/nv3uQLKAo2eRttyZ5kdVoXbqeKRswcjON2ylHvr1cW3yl5r3FoKfbwiLfqXYNhdjtfZYlmz6ENVzpOc7bgfkvKf4bM3zLwHTX51XzQ8Swk5gsNwUxVKZLG3RzL7CBP/ze8jjrrDGdCCl2aYuxj/FV8+xd39YQourvp5+kLDb5KkevZ3yQ80KBgPf1xkpXnDkuKRWTA4L+Hgn6z3btcMO/IOYQrUV5HXM0/3nuco+kgMgT/f6uU0IyTloIMSa9OKqhrIbXIGf2o3GkmKnqgaGUffAzegQB1nLTJ4nbYdwaqOGanQJTEnXvmJxl8ywXXGhkBBeRcZ8B9Dn9H0MVLOC7cl4d20q+4Y+6Wz044pkdKlPjJhpKWU/aE+CEEH9zFOqa05jE8jezwqnY2Na+P/zE23dkfBEvzP3aGBYAie0h9viA3unf9C02ZiivadnaqaaqR5JgsBT54xwrqPjG1uUrZHS9Oz/drtd57UEJ2j5vH6yqh+oYKGD4JvgFjVIVYTfRDqTyk2tUMe3sriZVxbWscRN27SF7tgOjDRrYK5kfoBeGQt8rVlkQEe8fE1FIQBiqRy1bgIrkunoQdT+C1PQu3VfCR30waWSxBjzAhqE0BbKnAV8FGu1BZZJzGJQ1+QRIl4B3FPlAlMKHLBDiZSr5MGhmCGtBQ91+AQD6FaDMFb82aPCEn5Izb+obiIy6hHaKjTyKdAWdBtaw3ssK64QIsuHvftQxaDe6PDB/fXa0XAC9YU+wME/9Swj8eh3jaB/52ZlSF8NN8IE6AS6pHmvsASRoMqC+EHPi2rAyParHLHZz66XbADyNmb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bitwarden-access-token
      namespace: external-secrets
