---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bitwarden-ids
  namespace: bitwarden-secrets
spec:
  encryptedData:
    organizationid: AgAxTFlKpgX+WXc86zSSgxZkvkmdCfimpbyU/ZchF88gQpEi3oeNM8xN4FBTwplwzbWDpnHeY+zHnUfjCfKLfdb8cp7Thb43GqGAMkf4nJs82OrO2leyAK8ALJfgj0Ewa7AxR3JJJxXE8Daz+OxY+7G87cW8qjUG0uv0GyucSCoMfl7FzRAvrIppin0mwriZpNhFRHzcLB9n+QNYnhSASyLtu2qhSYG7PV1C1DBTzUWloeObtZoHhEWc/UoU147UU46T7TtCoVJ+3OAi5rznrpLEJpTHIsnCdQAEOrnSqE5/zrvun3CrrxAneJwIm0sRPWIKnqrbg6Y+FfrbVwBxzc5XBYC2fJZY2NVpV+f6uHYEBCi1DhagTxlunA+l03V2c6AJI66sRY0gt1uBKZkSAPIP2eNT8mELNRf7dGFYsQoAPziTh1PDTJDgrGPFaJeE6PLef4W/gVYqHy647SNjLDJEfW5iYb3dAY6TLH08aNT7haAmT5raga0QKDcSENDiRGhefYGWVrz45aqcTCcf5y1q26hcLv1Q10DE+5P5PzN3hZ2mEg4+Pih7bavCJ2EFrcmBQh1tSdduf+ai/IsjrhbSztaVqROOCNy4wMY+097JpFbO5imZUwpz3slbrimFvAF7Lt2AqvCgXnP9OJ0lSjThx26/QqGkZYtPPzIXPDAYMW5HBnXdQkUXtyf36aY7G/SN9OsR7tgLdteh5xh679B+yjYG7knP2DiaknZXMa0aZuEcLfI=
    projectid: AgBppXoSkSA0WHDMDZpXHCK8o7jWOFfWl2fVuSjyuFHxA1VDK02DMPzvQlVKYU1Z+hc7LBp6DD5Ins044k49zLke9nwH8sy/UvylMhWBTFnPIiZYzbmIM8pJL08i6t2uGX6SH4e+zMi+Jb1hEy177PnPo0VchtNOSGkZWWt1NgleZbcIOCLQr3yblacjkye1ONmBZd3ZyUtYcC9fYN9KhnpYbqt4OU6euty+9r/C5F7TnSX1AMRq0eWxvXytAT1v6CPr5fBjUJ4KBkJcRe8mTvKNw+mUSTOlwzFUNZlCYnS/+nPJP1U6APKbtHQswJbWVdm0V5EFhicXIAEkj5V4qCnZqICGKJo9ShNCP5MS4YvygrrSoIWnBC4LqoAOiAthQvPT2GcHrbdNPf7lYIbzoV7gObzj5NUza2iM3Ip1D72iB2EyX+H/pigOLV8GFL/o4oyYgtRiF+2EXI+KC1/9+sGDZPSiwv0kjk7m5XXnK1V7o+d4s17tL1y/tw+ffVb+KGrLPIMiGh4Vz+YGqi6cfB3lJ+ogcYVewUH1z082m5a0g1kNoCXSCnG4WkNwFjvwPxC8RwIdFB9bDN+HqgS4pzf6h9Gs5WWqLRxRfkL9mdlAQVOR8M9U8ON9P+6iNCx2MbthVXQ2UAUehIukxViXrtSFf96HB0ftq/QwwWBKmzgWp13BvWW+5m3BZrkS8PG+cUXSCLBbDdB7XJp16lJ8R9jqm+ZHv6au4eOp6en3H/fFOhuJTfw=
  template:
    metadata:
      creationTimestamp: null
      name: bitwarden-ids
      namespace: bitwarden-secrets
    type: Opaque
