---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bitwarden-access-token
  namespace: operator
spec:
  encryptedData:
    token: AgABxSqN6Oco248r203W0HKoJv3PtGnfxjMwA/DmO4hvLkkPCl7sXcadRo+FmeZ9Egw4L3BzpNO/bVPKpdNnAwjKCdluM121wMsqYL1eEA1jS4/Y325AUI/Bn5YC9aU/vgNkH0/zaehonCG5r9jlw+m5J34l68Jh/bfiYLAljCsCJT1S1LbPaDpd/S8hGiLN+hlsgBNHB0WtCU2Sr2SzCMSaKcyzSyh7XqHfRpNbJg5eyzB4Ws9XPPBFE7TQ16cqhUGdyfT2ZXPIWpiJ2MWMYPUPMiqNMUWQgdM8aZD0FyhGFOvisHvtiZjvlSgYxRAmAo6RxUW5D+S1SWsDn7UfgkdZQPdktSrLiCQCGb/0ZW/zaMgdOEaoLqHWTzH2YTb19yYm7whF0x+DyYETpQcNboxGP3ztqkAVr2vaVONubHpox1LqSj0u+7Rz3W+9wxbWLDrVnw1sBDL3QnPQcBpRbab7Zlol5eXn2Les5O+8i1l2o98Ds4JvF2TivUlQ/hwCAbr/GLGWOlUvNYKH0Nkf3plF97qd/qieG/ymsnpNbbor/tRN0Uegf7k1XTpZkG1tQ1NXThwAJ2hhB8pt5Ukj+g+4Bjmmbao5KyyXn3SKTu9MV7oOae2ivroBGid+UHdoRLqjU4DLYB2afuGlEQT/Rn0MXWInpg0tAb/+69iavvcfJSV4AmC/HuodYK94jXwaCC5Ok9ruJqPiQ8OYjLVTPJ6j0Lou1mpasazAxhZ89j+InlT9IOWVv6yXGpABoYTrf2ZBSZ+no8B6WGKmMsPu+wSRdJAOlV4e35nWA8GBE5pOkBlfrpXrZsKRBuGmGch2
  template:
    metadata:
      creationTimestamp: null
      name: bitwarden-access-token
      namespace: operator
