---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bitwarden-ids
  namespace: bitwarden-secrets
spec:
  encryptedData:
    organizationid: AgDDkK5GMvQfbf5uzBTtFc3XNf6fV+DrTPVXYZHaYsqyhow784a8UntlE5rPOx2MaLD6k8OlakdBb/VGsQhSwNgNhQufdH/KMIHUDeKXuJHKA7XqYves6a4BzCwyraFpA3hU/DCSSFyfejgfE8dIgqPr2bgtfMT+OzW7tABYU/PY3WpbKZtb4cY83x16wpWhFOUuYBdlY135pQd7hYaYo2JwxbB6e0i6k0mXiplMduKjR9n09V3W9mX18zH5pEOCMhL7SGFDzNGp8OFFWqUiUR9WMkscXz+v57sczryD5dpDU9lHg2UHBVLbmpnwz1XCwH6zU0+TZIeEtuiROgLjXKg7cQ3FrUxfTplz/cU+f43H93JTn0kDEpwY6gANCYH5+xan5keUfEZT3sBXb2ci+aQT2FdCqYegB2skzM22DtqkojtBC1cDidekU2UR+uiu0tm09YqXLV06IGWjPTnLMzjZEJGlR8IY13fUtkCwdeXadbc4oEdMl4lwb3ReZwNYnncvL+BBy4B3NfLvpN5v3OQMVio0Te328W/7mpnpPA/dOymcLnlq1jLZ8k/T00CwDi/Y0q/CxsPsOQqlYxcQM+hlNDZhyPzLmlPq2qvllmqs/I/ufEXbUsWhE6NPnHqnjuPTwMUDPmvXK5/ALKaZDzu4yh8vrQnuhpHoRLK/GiHaptcymPUyTlhaxyztrovRUZjLDwN9Ue/evveiELNJys4JAT3vxl4PKB/hXkn1mClMFe0dpGU=
    projectid: AgCvAkac1J0oRo4hOnSMQD391Rx7VAKZZYMNG6SUKVmPwblvion3sgF3htYKwtp1GwWPhYlN6hmNBIzdwkOYHuug4dyK9IDizv9wPjXN4BGowAFJ8/TxEY9TEvKUFVWNAPN7g4HXi7JCKrHVKShLOwujJjkryCTDV7WQOaEB/Yv4KDBTgTlvVxFZVQTPykWnZKa+FsV1AmKcRY8Cchvl9IYkESZp7og8oSnDBuy2tpv0lNE1nr118B0PL1GE0OOOBiFjgn8ncXzAyRmFlovhEuan1qq4zziCmGsD70ndkQIImK/yFUAdfA1FMfEsDdYlo3RQf4yrKyY1Yfy2lYa9rchF2tR4A/0wKbDCWhOaN0GlLxYFEbp45IlUxvbYVDTSU0F69yMvsTd+aT7ngMpWYTxYllEgrQzSYc+NTuKOCu+3yxIc0qENJX9eecQa+etHpcHcL8Gjiyw+UDgauXB+UBwQrbjXFDRDfhRr6jyC3BlbgesUP7oJ8+dl4Qa2l/WmhpvIaSDENSI2ff+aG8qP562nHGbDeipHNOSc2t898k0wGTWvtLZ1em7Y5bdmUsGrvMVauXKrJecUcrfyOgJBahi1Bn9NSX6+3t+dKWQo+PG9OyEbEZ3D3+9oN4VqrwHIeVfK/GDf120Gx1+zN8ErNtrhdjHj+QxExmIJS+aazNmwQKB7oXdYvo+x9uZAsk7in/6QW7B76XqPKMs3oyRKiqw/IwAnxpwbTs22oIMdyf3e03YzVCE=
  template:
    metadata:
      creationTimestamp: null
      name: bitwarden-ids
      namespace: bitwarden-secrets
    type: Opaque
