apiVersion: v2
name: external-secrets-operator
description: External Secrets Operator for Kubernetes
version: 0.1.0
appVersion: "0.9.0"
dependencies:
  - name: external-secrets
    version: 0.9.0
    repository: https://charts.external-secrets.io
    condition: external-secrets.enabled
