apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml?ref=v1.8.2
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/dashboard-install.yaml?ref=v1.8.2

patches:
  - target:
      kind: Service
      name: argo-rollouts-dashboard
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          omni-kube-service-exposer.sidero.dev/port: "3100"
          omni-kube-service-exposer.sidero.dev/label: "Argo Rollouts"
 