apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Use a specific version instead of 'latest' for better reproducibility
  #- https://github.com/argoproj/argo-rollouts/releases/download/v1.8.2/namespace-install.yaml
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.8.2/install.yaml
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.8.2/dashboard-install.yaml
  # Local patch for ServiceAccount removal
  #- serviceaccount_removal.yaml

# Use the newer patches format instead of patchesJson6902
patches:
  - target:
      kind: Service
      name: argo-rollouts
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          omni-kube-service-exposer.sidero.dev/port: "3100"
          omni-kube-service-exposer.sidero.dev/label: "Argo Rollouts"
 