# Chart.yaml
apiVersion: v2
name: adguardns
description: A Helm umbrella chart to deploy AdGuardNS (AdGuard Home DNS blocker) without on-disk storage
type: application

version: 0.1.0
appVersion: "0.107.59"

dependencies:
  - name: adguard-home
    version: 0.21.0
    repository: https://helm-charts.rm3l.org
    # <-- this must match the *key* in values.yaml exactly
    condition: adguard-home.enabled
    tags:
      - dns

