# values.yaml
# ===============
# (No top-level image block — remove your myregistry.local reference)

# ==============================
# Enable the adguard-home subchart
# ==============================
adguard-home:
  enabled: true

  # ────────────────
  # NO on-disk storage
  # ────────────────
  persistence:
    enabled: false

  # ────────────────────────────────
  # Use the official AdGuard Home image from Docker Hub
  # ────────────────────────────────
  image:
    repository: adguard/adguardhome
    tag: "v0.107.59"        # or whatever tag matches appVersion
    pullPolicy: IfNotPresent

  # ────────────────────────────────
  # Inline configuration (all via config files)
  # ────────────────────────────────
  config:
    customConfig: |-
      upstream_dns:
        - "1.1.1.1"
        - "8.8.8.8"
      clients:
        local:
          - "192.168.0.0/16"
      blocklists:
        - "/etc/adguardns/blocklists/blocklist1.txt"
        - "/etc/adguardns/blocklists/blocklist2.txt"

  # ────────────────────────────────
  # (Optional) mount extra configMap for blocklists
  # ────────────────────────────────
  extraVolumes:
    - name: config-files
      configMap:
        name: adguardns-extra-config
  extraVolumeMounts:
    - name: config-files
      mountPath: /etc/adguardns/blocklists
      readOnly: true

  service:
    type: ClusterIP
    port: 53

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

