---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows #project manifest hardcodes 'argo' by default, legacy of workflows being their first project

commonLabels:
  app.kubernetes.io/name: argo-workflows

resources:
- ./namespace.yaml
- https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/install.yaml

patches:
  - target:
      kind: Service
      name: argo-server
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          omni-kube-service-exposer.sidero.dev/port: "50085"
          omni-kube-service-exposer.sidero.dev/label: "Argo Workflows"
          omni-kube-service-exposer.sidero.dev/prefix: argoworkflows

#https://argoproj.github.io/argo-workflows/argo-server-auth-mode/
  - patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value:
        --auth-mode
    - op: add
      path: "/spec/template/spec/containers/0/args/-"
      value:
        server
    target:
      kind: Deployment
      name: argo-server
