apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  template:
    spec:
      containers:
      - name: operator  # Add container name
        env:
        - name: OPERATOR_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: tailscale-credentials
              key: clusterName