apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/heads/main/cmd/k8s-operator/deploy/manifests/operator.yaml?ref=v1.84.3
  - tailscale-secret.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: operator