apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/heads/main/cmd/k8s-operator/deploy/manifests/operator.yaml?ref=v1.84.3
  - tailscale-secrets.yaml
  - tailscale-oauth.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: OPERATOR_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: tailscale-credentials
              key: clusterName