apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/tailscale/tailscale-operator?ref=v1.84.3
  - template/tailscale-secret.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: operator