apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/instance: tailscale
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: tailscale
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/instance: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-operator
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/instance: tailscale
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get", "list", "watch"]
- apiGroups: ["tailscale.com"]
  resources: ["connectors"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["tailscale.com"]
  resources: ["connectors/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["tailscale.com"]
  resources: ["proxies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/instance: tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-operator
subjects:
- kind: ServiceAccount
  name: operator
  namespace: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/instance: tailscale
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/instance: tailscale
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/instance: tailscale
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: operator
      containers:
      - name: operator
        image: ghcr.io/tailscale/tailscale-operator:v1.84.3
        env:
        - name: TS_KUBE_SECRET
          value: tailscale-auth
        - name: OPERATOR_HOSTNAME
          value: "" # This will be patched by Kustomize
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 3000
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 3000
