apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
  namespace: tailscale
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: clientid
      remoteRef:
        key: ts_clientId
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: clientsecret
      remoteRef:
        key: ts_clientSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: clusterName
      remoteRef:
        key: ts_clusterName
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None