apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: client_id
      remoteRef:
        key: ts_clientId
    - secretKey: client_secret
      remoteRef:
        key: ts_clientSecret