apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
  namespace: tailscale
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: clientid
      remoteRef:
        key: ts_clientId
    - secretKey: clientsecret
      remoteRef:
        key: ts_clientSecret
    - secretKey: clusterName
      remoteRef:
        key: ts_clusterName