# values.yaml
tailscale-operator:
  installCRDs: true
  
  # OAuth configuration
#  oauth:
#    clientId: ""  # Will be set from environment variables
#    clientSecret: ""  # Will be set from environment variables
