# Enable the Tailscale operator
tailscale-operator:
  enabled: true
  image:
    repository: ghcr.io/tailscale/tailscale
    tag: v1.0.0
    pullPolicy: IfNotPresent
  
  # These values will be populated from ExternalSecret
  config:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: tailscale-credentials
            key: clientId
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: tailscale-credentials
            key: clientSecret
    
    # Cluster name from the same secret
    clusterName:
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clusterName
  
  # Default values for the operator
  operator:
    logLevel: info
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  
  # Resource limits and requests
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

