# Enable the Tailscale operator
tailscale-operator:
  installCRDs: true
  
  # These values will be populated from ExternalSecret
  oauth:
    clientId:
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clientId
    clientSecret:
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clientSecret
    
    # Cluster name from the same secret
  
  # Default values for the operator
  operatorConfig:
    hostname:
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clusterName
  
  # Resource limits and requests
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

