# values.yaml
tailscale-operator:
  installCRDs: true
  
  # OAuth configuration
  oauth:
    clientId: ""  # Will be set from environment variables
    clientSecret: ""  # Will be set from environment variables
  
  # Operator configuration
  operatorConfig:
    hostname: ""  # Will be set from environment variables
  
  # Environment variables for the operator
  env:
    - name: TS_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clientId
    - name: TS_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clientSecret
    - name: TS_HOSTNAME
      valueFrom:
        secretKeyRef:
          name: tailscale-credentials
          key: clusterName
  

  # Resource limits and requests
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

