apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitwarden-credentials
  namespace: external-secrets
spec:
  encryptedData:
    client-id: <your-encrypted-client-id>
    client-secret: <your-encrypted-client-secret>
  template:
    metadata:
      name: bitwarden-credentials
      namespace: external-secrets
    type: Opaque
