apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: cloudflare-operator
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cf_k8sOperator

