---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

commonLabels:
  app.kubernetes.io/name: argo-events

resources:
  - ./namespace.yaml
  - https://github.com/argoproj/argo-events/releases/download/v1.9.5/install.yaml
  - https://github.com/argoproj/argo-events/releases/download/v1.9.5/install-validating-webhook.yaml
